name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [arcade]
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to arcade server
        run: cp index.html /home/arcade/app/index.html